### ISSUE TITLE
Error "catkin_make" about the SGBA 

### ISSUE THREAD

**Issue by lilin-ll** [tudelft/SGBA_code_SR_2019#5]
After putting the repositories into the ` /home/work/SGBA/src` directory , I have tried:
`cakin_make`

with the following results:
`In file included from /home/work/SGBA/src/argos_bridge/plugin/simulation/argos_ros_start_simulation.cpp:8:0:
/home/work/SGBA/src/argos_bridge/plugin/simulation/argos_ros_start_simulation.h:16:31: fatal error: neat_ros/StartSim.h: No such files or directory
compilation terminated.
argos_bridge/plugin/CMakeFiles/argos_ros_start_sim_server.dir/build.make:62: recipe for target 'argos_bridge/plugin/CMakeFiles/argos_ros_start_sim_server.dir/simulation/argos_ros_start_simulation.cpp.o' failed
make[2]: *** [argos_bridge/plugin/CMakeFiles/argos_ros_start_sim_server.dir/simulation/argos_ros_start_simulation.cpp.o] Error 1
In file included from /home/work/SGBA/src/argos_bridge/plugin/simulation/argos_ros_start_simulation.cpp:8:0:
/home/work/SGBA/src/argos_bridge/plugin/simulation/argos_ros_start_simulation.h:16:31: fatal error: neat_ros/StartSim.h: No such files or directoryted.
`

Any idea what is going on?

Thanks

**Comment by knmcguire** [comment]
Technically you wouldn't need the neat_ros/StartSim.h. Have you tried to remove it?

**Comment by lilin-ll** [comment]
Thank you very much for your reply!
I tried to comment out ` neat_ros/StartSim.h` in the file `argos_ros_start_simulation.h`, but a new error occurred:

`In file included from /home/work/SGBA/src/argos_bridge/plugin/simulation/argos_ros_start_simulation.cpp:8:0:
/home/work/SGBA/src/argos_bridge/plugin/simulation/argos_ros_start_simulation.h:34:16: error: ‘neat_ros’ has not been declared
 bool start_sim(neat_ros::StartSim::Request  &req,
                ^
/home/work/SGBA/src/argos_bridge/plugin/simulation/argos_ros_start_simulation.h:34:46: error: ‘req’ was not declared in this scope
 bool start_sim(neat_ros::StartSim::Request  &req,
`
I observe that all these errors are related to the `argos_bridge`. Is it necessary to do anything else with the argos_bridge?

**Comment by knmcguire** [comment]
It depends. Argos bridge is what connects Argos (the simulation environment) with ROS, which is necesary if you want to try out the simulation. It seems that there is a custom ros service (StartSim.srv) that belongs to neat_ros that is not available in this repo. But it can be replaced by a srv message in the repositories that are in this one. It just needs to contain this content:
```

int32 regenerate_env
int32 select_env
int32 trial_num
---
```

I will try to start up an virtual environment to get this running again. This worked on ubuntu 16.04 and currently I'm working on a machine with 18.04
